# Generated by Django 5.0.6 on 2024-07-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='income',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='save',
            field=models.FloatField(),
        ),
    ]
